import Container from '@/components/layout/Container';
import { Caption, Typography } from '@/components/typography/typography';
import Avatar from '@/components/ui/custome/Avatar';
import ProductCard from '@/components/ui/custome/ProductCard';
import { ProfileCard } from '@/components/ui/custome/ProfileCard';
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


function page() {
  return (
    <Container className='flex justify-end items-center'>

      <ProfileCard variant='right' />
      <ProfileCard variant='left'/>
    </Container>
  )
}

export default page