import Container from '@/components/layout/Container';
import { Caption, Typography } from '@/components/typography/typography';
import AnalyticsCard from '@/components/ui/custome/AnalyticsCard';
import Avatar from '@/components/ui/custome/Avatar';
import ProductCard from '@/components/ui/custome/ProductCard';
import { ProfileCard } from '@/components/ui/custome/ProfileCard';
import { Users } from 'lucide-react';
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


function page() {
  return (
    <Container>
      <Container className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4'>
        <Container padding='md' variant='primary' radius='xl'>
          <Typography variant='h3' weight='extrabold'>2567</Typography>
          <Typography variant='h6'>Users</Typography>
          <Typography variant='overline'>New Users</Typography>
        </Container>
        
        <Container padding='md' variant='primary' radius='xl'>
          <Typography variant='h3' weight='extrabold'>2567</Typography>
          <Typography variant='h6'>Users</Typography>
          <Typography variant='caption'>New Users</Typography>
        </Container>
        
        <Container padding='md' variant='primary' radius='xl'>
          <Typography variant='h3' weight='extrabold'>2567</Typography>
          <Typography variant='h6'>Users</Typography>
          <Typography variant='caption'>New Users</Typography>
        </Container>
        
        <Container padding='md' variant='primary' radius='xl'>
          <Typography variant='h3' weight='extrabold'>2567</Typography>
          <Typography variant='h6'>Users</Typography>
          <Typography variant='caption'>New Users</Typography>
        </Container>
        
        <Container padding='md' variant='primary' radius='xl'>
          <Typography variant='h3' weight='extrabold'>2567</Typography>
          <Typography variant='h6'>Users</Typography>
          <Typography variant='caption'>New Users</Typography>
        </Container>
        
      </Container>
    </Container>
  )
}

export default page